### ISSUE TITLE
Ligths does not work in Firefox 71.0 (64 bits) Desktop

### ISSUE THREAD

**Issue by iocodz** [matias-carpintini/hydracss#6]
When I try to switch between dark and ligth nothing happens

**Comment by matias-carpintini** [comment]
Try clearing cache.

**Comment by iocodz** [comment]
Perfect, do you know why that happens?

**Comment by matias-carpintini** [comment]
Cool! Yes, the assets provider by CDN keep saved for a lot of time in the browser. I need fix that.
